steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/visionunlocked', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/visionunlocked']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'visionunlocked', '--image', 'gcr.io/$PROJECT_ID/visionunlocked', '--region', 'us-central1', '--platform', 'managed']

images:
- 'gcr.io/$PROJECT_ID/visionunlocked'
